# Generated by Django 4.1.7 on 2023-05-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dev_status",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Статус пристрою"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dev_type",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Тип пристрою"
                    ),
                ),
                (
                    "dev_type_logo",
                    models.FileField(
                        default="dev_type.jpg",
                        upload_to="dev_types/",
                        verbose_name="Лого категорії",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceWarranty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        default="Без гарантії",
                        max_length=100,
                        unique=True,
                        verbose_name="Термін гарантії",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Назва постачальника"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        null=True, unique=True, verbose_name="Посилання на сайт"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Електрона пошта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="Номер телефону"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        max_length=500, null=True, verbose_name="Коментарі"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Назва виробника"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        null=True, unique=True, verbose_name="Посилання на сайт"
                    ),
                ),
                (
                    "vendor_logo",
                    models.FileField(
                        default="dev_vendor.jpg",
                        upload_to="vendors/",
                        verbose_name="Лого виробника",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_title",
                    models.CharField(max_length=250, verbose_name="Назва пристрою"),
                ),
                (
                    "device_model",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Модель пристрою"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        default="No Serial",
                        max_length=30,
                        verbose_name="Серійний номер",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(null=True, verbose_name="Дата придбання"),
                ),
                (
                    "comments",
                    models.TextField(
                        max_length=500, null=True, verbose_name="Коментарі"
                    ),
                ),
                (
                    "device_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.devicestatus",
                        verbose_name="Статус пристрою",
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.devicetype",
                        verbose_name="Тип пристрою",
                    ),
                ),
                (
                    "device_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.vendors",
                        verbose_name="Виробник",
                    ),
                ),
                (
                    "device_warranty",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.devicewarranty",
                        verbose_name="Термін гарантії",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.suppliers",
                        verbose_name="Постачальник",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employees",
                        verbose_name="Користувач",
                    ),
                ),
            ],
        ),
    ]
