# Generated by Django 4.1.7 on 2023-05-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        default="def-logo.jpg",
                        upload_to="company/",
                        verbose_name="Логотип компанії",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Назва компанії"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Код ЄДРПОУ"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=250, null=True, verbose_name="Адреса"),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Електрона пошта"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Телефон компанії"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        default="null",
                        max_length=500,
                        null=True,
                        verbose_name="Коментарі",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.cities",
                        verbose_name="Місто",
                    ),
                ),
                (
                    "p_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employees",
                        verbose_name="МВ Особа",
                    ),
                ),
            ],
        ),
    ]
