# Generated by Django 4.1.7 on 2023-05-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="comments",
            field=models.TextField(max_length=500, null=True, verbose_name="Коментарі"),
        ),
    ]
