# Generated by Django 4.1.7 on 2023-05-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("company", "0002_alter_company_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(
                default="", max_length=250, null=True, verbose_name="Адреса"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                default=-1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.cities",
                verbose_name="Місто",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="comments",
            field=models.TextField(
                default="", max_length=500, null=True, verbose_name="Коментарі"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.CharField(
                default="", max_length=150, null=True, verbose_name="Електрона пошта"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="p_owner",
            field=models.ForeignKey(
                default=-1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.employees",
                verbose_name="МВ Особа",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(
                default="", max_length=20, null=True, verbose_name="Телефон компанії"
            ),
        ),
    ]
