# Generated by Django 4.1.7 on 2023-05-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("company", "0003_alter_company_address_alter_company_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="logo",
            new_name="company_logo",
        ),
        migrations.RemoveField(
            model_name="company",
            name="p_owner",
        ),
        migrations.RemoveField(
            model_name="company",
            name="title",
        ),
        migrations.AddField(
            model_name="company",
            name="company_boss",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_boss",
                to="employees.employees",
                verbose_name="Директор",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_title",
            field=models.CharField(
                default="", max_length=200, unique=True, verbose_name="Назва компанії"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="product_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_owner",
                to="employees.employees",
                verbose_name="МВ Особа",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=250, null=True, verbose_name="Адреса"),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.cities",
                verbose_name="Місто",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="comments",
            field=models.TextField(
                default="",
                max_length=500,
                null=True,
                verbose_name="Додаткові коментарі:",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_code",
            field=models.CharField(
                default="", max_length=8, unique=True, verbose_name="Код ЄДРПОУ"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, verbose_name="Електрона пошта"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
